Update commit-check.yml

diff --git a/.github/workflows/commit-check.yml b/.github/workflows/commit-check.yml
--- a/.github/workflows/commit-check.yml
+++ b/.github/workflows/commit-check.yml
@@ -1,22 +1,28 @@
 name: "Commit Message Check"
-
-on:
-  pull_request:
-    types: [opened, edited, synchronize]
+on: [pull_request]
 
 jobs:
-  check-commit-format:
+  check:
     runs-on: ubuntu-latest
     steps:
-      - name: Check Commit Message Format and Length
-        uses: gs0604/commit-message-checker@v2
+      - uses: actions/checkout@v4
         with:
-          # Regex Explained:
-          # ^#\d+     -> Starts with # and at least one digit (the ID)
-          # ,         -> Followed exactly by a comma
-          # \s        -> Followed exactly by a space
-          # .{1,20}   -> Followed by 1 to 20 characters of message
-          # $         -> End of string
-          pattern: '^#\d+, \s*.{1,22}$'
-          error: 'Commit message format error! Expected format: "#ID, Your message" (Max 30 characters total).'
-          excludeDescription: 'true'
+          fetch-depth: 0
+
+      - name: Validate Commit Message
+        run: |
+          # Take the title of last commit
+          MSG=$(git log -1 --pretty=%s)
+          echo "Check the message: $MSG"
+          
+          # Regex: ^# (start with #), [0-9]+ (one or more numbers), , (comma), \  (space)
+          if [[ ! $MSG =~ ^#[0-9]+,\ .+$ ]]; then
+            echo "ERROR: Message must be in format '#123, text'"
+            exit 1
+          fi
+          
+          # Chec the lenght
+          if [ ${#MSG} -gt 30 ]; then
+            echo "ERROR: Message too long (max 40 characters)."
+            exit 1
+          fi
